// ==== PREGUNTAS ====
const questions = [
  /*1*/ { q: "¿Cuántos libros tiene la Biblia en total??", a: ["39","66","69"], c: 1, difficulty: "facil" },
  /*2*/ { q: "¿Cuántas personas se salvaron en el arca de Moisés?", a: ["1", "8", "4"], c: 0, difficulty: "facil"},
  /*3*/ { q: "¿Qué juez de Israel tenía una fuerza extraordinaria?", a: ["Gedeón", "Sansón", "Goliat"], c: 1, difficulty: "facil"},
  /*4*/ { q: "¿Qué rey pidió sabiduría en vez de riquezas?", a: ["David", "Josías", "Salomón"], c: 2, difficulty: "facil"},
  /*5*/ { q: "¿Qué apóstol negó a Jesús 3 veces?", a: ["Tomás", "Pedro", "Judas"], c: 1, difficulty: "facil"},
  /*6*/ { q: "¿En qué año empezó a gobernar en el cielo el Reino de Dios?", a: ["1914", "1916", "33"], c: 0, difficulty: "facil"},
  /*7*/ { q: "¿Cómo se llama el grupo de personas que dirige la organización a nivel mundial?", a: ["Ancianos de congregación", "Ungidos", "Cuerpo Gobernante"], c: 2, difficulty: "facil"},
  /*8*/ { q: "¿Cuántos hombre escribieron la Biblia?", a: ["44", "33", "40"], c: 2, difficulty: "facil"},
  /*9*/ { q: "Cierto o falso. El número <span class='resaltar'> total </span> de los hijos e hijas de Jacob fue de 12", a: ["Cierto", "Falso"], c: 1, difficulty: "facil"},
 /*10*/ { q: "¿Cuál es el séptimo libro de la Biblia?", a: ["Josué", "Esdras", "Jueces"], c: 2, difficulty: "facil"},
 /*11*/ { q: "¿Cuál es el libro de la Biblia que tiene más capítulos?", a: ["Salmos", "Proverbios", "Números"], c: 0, difficulty: "facil"},
 /*12*/ { q: "¿Cómo se les conoce a las 4 letras hebreas del nombre de Dios?", a: ["Pentagramaton", "Tetragrámaton", "Consonantes"], c: 1, difficulty: "facil"},
 /*13*/ { q: "¿Cuántas veces aparece el nombre de Dios en la Biblia?", a: ["144.000", "156", "7.000"], c: 2, difficulty: "facil"},
 /*14*/ { q: "¿Qué es el Reino de Dios?", a: ["Un gobierno simbólico", "Un gobierno celestial", "Algo en el corazón"], c: 1, difficulty: "facil"},
 /*15*/ { q: "¿En qué año se adoptó el nombre de Testigos de Jehová?", a: ["1931", "1914", "1824"], c: 0, difficulty: "facil"},


  /*1*/ { q: "El Alfa y el Omega son títulos de…", a: ["Jesús","Jehová","Satanás"], c: 1, difficulty: "media" },
  /*2*/ { q: "La viuda que observó Jesús en el templo echo...", a: ["Un denario", "Un leptón", "Un talento", "Un cuadrante"], c: 3, difficulty: "media"},
  /*3*/ { q: "¿Cuántos libros tienen las Escrituras Griegas Cristianas?", a: ["29", "33", "27", "19"], c: 2, difficulty: "media"},
  /*4*/ { q: "¿Cuáles son los nombres de los 4 ríos del Edén?", a: ["Pisón, Jordán, Hidequel (Tigris) y Éufrates. ", "Pisón, Guihon, Hidequel (Tigris) y Éufrates. ", "Abaná, Farpar, Hidequel (Tigris) y Éufrates. ", "Pisón, Nilo, Tigris y Éufrates. "], c: 1, difficulty: "media"},
  /*5*/ { q: "¿Quién escribió la mayoría de los Salmos?", a: ["Moisés", "Asaf", "Salomón", "Jonatán", "David"], c: 4, difficulty: "media"},
  /*6*/ { q: "¿En qué monte recibió Moisés los Diez Mandamientos?", a: ["Monte Carmelo", "Monte de Edom", "Monte Elevado", "Monte Sinaí", "Monte Guilgal"], c: 3, difficulty: "media"},
  /*7*/ { q: "Cierto o Falso. Homer fué la esposa de Oseas", a: ["Falso", "Cierto"], c: 0, difficulty: "media"},
  /*8*/ { q: "¿Con qué otro nombre se le conoce al lago de fuego?", a: ["El abismo", "La muerte celestial", "La muerte segunda", "El abismo ardiente", "El lamento eterno"], c: 2, difficulty: "media"},
  /*9*/ { q: " Leviatán es un tipo de animal...", a: ["Acuático", " Terrestre", "Aéro", "Aéreo-terrestre"], c: 0, difficulty: "media"},
 /*10*/ { q: "¿Con qué nombre se le conocía antes a la revista Despertad?", a: ["Eternal life", "The word of God", "A cry from the sky", "Zion's Watch Tower", "The Golden Age"], c: 4, difficulty: "media"},
 /*11*/ { q: "¿En qué año se dijo esta frase: 'Anuncien, anuncien, anuncien al Rey y su reino'?", a: ["2000", "1914", "1931", "1922", "1919"], c: 3, difficulty: "media"},
 /*12*/ { q: "¿Con qué nombre se le conocía antes a los precursores?", a: ["Subditos", "Gramofoneros", "Predicadores", "Ministros", "Colportores"], c: 4, difficulty: "media"},
 /*13*/ { q: "¿A quién representa en el hombre con el tintero de Secretario?", a: ["A los ungidos que quedan en la tierra", "A Jesús", "A Jehová", "A los ángeles", "A los ancianos de congregación"], c: 1, difficulty: "media"},
 /*14*/ { q: "¿Cómo se les conocía antes a los superintendentes de circuito?", a: ["Viajeros", "Enviados", "Nobles", "Peregrinos", "Portavoces"], c: 3, difficulty: "media"},
 /*15*/ { q: " ¿Cómo se le conoce ahora a lo que antes le llamaba Círculos Bereanos para Estudios Bíblicos?", a: ["Cursos bíblicos", "Reunión Vida y Ministerio Cristianos", "Discurso Público", "Estudio Bíblico de la Congregación"], c: 3, difficulty: "media"},


  /*1*/ { q: "¿Cuáles son los cinco gobernantes egipcios (faraones) que la Biblia menciona por nombre?", a: ["Sisac, So, Tirhacá, Nekó y Hofrá", "So, Nabucodonosor, Ciro, Tirhacá y Darío", "Sisac, So, Tirhacá, Senaquerib y Hofra"], c: 0, difficulty: "dificil" },
  /*2*/ { q: "¿Cuándo se celebraba la Fiesta de las Cabañas?", a: ["Del 10 al 21 de etanim", "Del 14 al 16 de Nisán", "Del 1 al 11 de Kislev", "Del 15 al 21 de etanim", "No se sabe la fecha exacta"], c: 3, difficulty: "dificil"},
  /*3*/ { q: "¿Cómo se llamó el primer cancionero de los Testigos de Jehová?", a: ["Cantemos Juntos", "Alabanzas para Dios", "Cánticos de la Novia", "¡A Dios Alabad!", "Cancionero Cristiano"], c: 2, difficulty: "dificil"},
  /*4*/ { q: "¿Cuántos tipos de ofrenda se mencionan en la Biblia?", a: ["10", "12", "7", "8", "9"], c: 3, difficulty: "dificil"},
  /*5*/ { q: "¿En qué año entró en vigor el año el Pacto Abrahámico?", a: ["1527 a.e.c", "1919 e.c", "1647 a.e.c", "1943 e.c", "1943 a.e.c"], c: 4, difficulty: "dificil"},
  /*6*/ { q: "¿Cuáles eran las tres grandes Fiestas de la Ley mosaica?", a: ["La Fiesta de las Tortas no Fermentadas, La Fiesta de las Cabañas, La Fiesta de las Primicias", "La Fiesta del Arrepentimiento, La Fiesta de las Cabañas, La Fiesta de las Semanas ", "La Fiesta de las Tortas no Fermentadas, La Fiesta de las Cabañas, La Fiesta de las Semanas", "La Fiesta del Pacto, La Fiesta de las Cabañas, La Fiesta de las Ofrendas"], c: 2, difficulty: "dificil"},
  /*7*/ { q: "El Urim y el Tumim eran objetos usados por...", a: ["El rey de la nación", "Los fariseos", "Los israelitas rebeldes", "Las naciones paganas", "El sumo sacerdote"], c: 4, difficulty: "dificil"},
  /*8*/ { q: "Nombre del mes hebreo que se añadía 7 veces en 19 años", a: ["Elul", "Veadar", "Hesván", "Sebat", "Tamuz"], c: 1, difficulty: "dificil"},
  /*9*/ { q: "¿Cuando entro en vigor el cambio en las reuniones para poder celebrar la Noche de Adoración en Familia?", a: ["1 de enero de 2010", "1 de septiembre de 2010", "1 de enero de 2009", "1 de septiembre de 2009", "1 Octubre de 2010"], c: 3, difficulty: "dificil"},
 /*10*/ { q: "¿Cuándo se celebró por ultima vez la navidad en el Betel de Brooklyn?", a: ["Nunca se celebró", "1924", "1926", "1919", "1914"], c: 2, difficulty: "dificil"},
 /*11*/ { q: "Cierto o Falso. Antes, los ancianos de congregación eran seleccionados por votación", a: ["Falso", "Cierto"], c: 1, difficulty: "dificil"},
 /*12*/ { q: "¿Cuál es el significado bíblico del término Seol?", a: ["Lugar de castigo eterno", "Abismo espiritual", "Lago de Fuego", "Tumba", "Muerte Segunda"], c: 3, difficulty: "dificil"},
 /*13*/ { q: "Cierto o Falso. A partir de 1891 empezó a aparecer en la portada de la revista Watch Tower el emblema de una cruz y una corona", a: ["Cierto", "Falso"], c: 0, difficulty: "dificil"},
 /*14*/ { q: "¿A cuántos años equivale la profecía de los Siete Tiempoos?", a: ["490 años", "2.200 años", "1.260 años", "2.520 años", "500 años"], c: 3, difficulty: "dificil"},
 /*15*/ { q: "¿Quién es el esclavo fiel y prudente?", a: ["Todos los ungidos de la tierra", "Los ungidos en el cielo", "Los miembros del Cuerpo Gobernante", "Todos los que sirven en Betel"], c: 2, difficulty: "dificil"},
 /*16*/ { q: "¿Qué opción describe en orden exacto la jerarquía de los ángeles?", a: ["Arcángel, Serafín, Querubín, Mensajero", "Querubín, Arcángel, Mensajero, Serafín", "No existe jerarquía", "No se sabe", "Arcángel, Querubín, Serafín, Mensajero"], c: 4, difficulty: "dificil"},
 /*17*/ { q: "¿Cuál de estas afirmaciones sobre Miguel es correcta?", a: ["Es Jesús en existencia prehumana", "Es uno de los 144,000", "No existe", "Es un ángel más", "Es otro título de Dios"], c: 0, difficulty: "dificil"},
 /*18*/ { q: "¿Qué evento marcará el fin definitivo de Satanás?", a: ["Liberación final tras mil años", "Armagedón", "Juicio Inicial", "Primera resurrección", "No se sabe"], c: 0, difficulty: "dificil"},
 /*19*/ { q: "Según Mateo 24:34, “esta generación” se refiere a:", a: ["Los que vivieron en 33 e.C", "Dos grupos superpuestos de ungidos", "Los que vivieron en 1914", "Generación simbólica", "Los discípulos de Jesús"], c: 1, difficulty: "dificil"},
 /*20*/ { q: "Según Mateo 17:24-27, Pedro encontró una moneda en la boca de un pez. ¿Cuál era la función principal de esa moneda?", a: ["Comprar comida para los discípulos", "Mostrar a los fariseos que Jesús podía hacer milagros", "Pagar el impuesto del templo por Jesús y Pedro", "Mostrar la inscripción del César", "Pagarle a Pedro su día escaso de pesca"], c: 2, difficulty: "dificil"},

 
];