const questionsDificil = [

  /*1*/ { q: "¿Cuáles son los cinco gobernantes egipcios (faraones) que la Biblia menciona por nombre?", a: ["Sisac, So, Tirhacá, Nekó y Hofrá", "So, Nabucodonosor, Ciro, Tirhacá y Darío", "Sisac, So, Tirhacá, Senaquerib y Hofra"], c: 0, difficulty: "dificil" },
  /*2*/ { q: "¿Cuándo se celebraba la Fiesta de las Cabañas?", a: ["Del 10 al 21 de etanim", "Del 14 al 16 de Nisán", "Del 1 al 11 de Kislev", "Del 15 al 21 de etanim", "No se sabe la fecha exacta"], c: 3, difficulty: "dificil"},
  /*3*/ { q: "¿Cómo se llamó el primer cancionero de los Testigos de Jehová?", a: ["Cantemos Juntos", "Alabanzas para Dios", "Cánticos de la Novia", "¡A Dios Alabad!", "Cancionero Cristiano"], c: 2, difficulty: "dificil"},
  /*4*/ { q: "¿Cuántos tipos de ofrenda se mencionan en la Biblia?", a: ["10", "12", "7", "8", "9"], c: 3, difficulty: "dificil"},
  /*5*/ { q: "¿En qué año entró en vigor el año el Pacto Abrahámico?", a: ["1527 a.e.c", "1919 e.c", "1647 a.e.c", "1943 e.c", "1943 a.e.c"], c: 4, difficulty: "dificil"},
  /*6*/ { q: "¿Cuáles eran las tres grandes Fiestas de la Ley mosaica?", a: ["La Fiesta de las Tortas no Fermentadas, La Fiesta de las Cabañas, La Fiesta de las Primicias", "La Fiesta del Arrepentimiento, La Fiesta de las Cabañas, La Fiesta de las Semanas ", "La Fiesta de las Tortas no Fermentadas, La Fiesta de las Cabañas, La Fiesta de las Semanas"], c: 2, difficulty: "dificil"},
  /*7*/ { q: "El Urim y el Tumim eran objetos usados por...", a: ["El rey de la nación", "Los fariseos", "Los israelitas rebeldes", "Las naciones paganas", "El sumo sacerdote"], c: 4, difficulty: "dificil"},
  /*8*/ { q: "Nombre del mes hebreo que se añadía 7 veces en 19 años", a: ["Elul", "Veadar", "Hesván", "Sebat", "Tamuz"], c: 1, difficulty: "dificil"},
  /*9*/ { q: "¿Cuando entro en vigor el cambio en las reuniones para poder celebrar la Noche de Adoración en Familia?", a: ["1 de enero de 2010", "1 de septiembre de 2010", "1 de enero de 2009", "1 de septiembre de 2009", "1 Octubre de 2010"], c: 3, difficulty: "dificil"},
 /*10*/ { q: "¿Cuándo se celebró por ultima vez la navidad en el Betel de Brooklyn?", a: ["Nunca se celebró", "1924", "1926", "1919", "1914"], c: 2, difficulty: "dificil"},
 /*11*/ { q: "Cierto o falso: antes, los ancianos de congregación eran seleccionados por votación", a: ["Falso", "Cierto"], c: 1, difficulty: "dificil"},
 /*12*/ { q: "¿Cuál es el significado bíblico del término Seol?", a: ["Lugar de castigo eterno", "Abismo espiritual", "Lago de Fuego", "Tumba", "Muerte Segunda"], c: 3, difficulty: "dificil"},
 /*13*/ { q: "Cierto o falso: a partir de 1891 empezó a aparecer en la portada de la revista Watch Tower el emblema de una cruz y una corona", a: ["Cierto", "Falso"], c: 0, difficulty: "dificil"},
 /*14*/ { q: "¿A cuántos años equivale la profecía de los Siete Tiempos?", a: ["490 años", "2.200 años", "1.260 años", "2.520 años", "500 años"], c: 3, difficulty: "dificil"},
 /*15*/ { q: "¿Quién es el esclavo fiel y prudente?", a: ["Todos los ungidos de la tierra", "Los ungidos en el cielo", "Los miembros del Cuerpo Gobernante", "Todos los que sirven en Betel"], c: 2, difficulty: "dificil"},
 /*16*/ { q: "¿Qué opción describe en orden exacto la jerarquía de los ángeles?", a: ["Arcángel, Serafín, Querubín, Mensajero", "Querubín, Arcángel, Mensajero, Serafín", "No existe jerarquía", "No se sabe", "Arcángel, Querubín, Serafín, Mensajero"], c: 4, difficulty: "dificil"},
 /*17*/ { q: "En la tienda se escondió con gran valor, ofreció hospitalidad y luego dio terror. Muchos creen que la guerra la hicieron soldados, pero ¿quién terminó con Sísara cuando todos estaban cansados?", a: ["Jael", "Débora", "Abigail", "Orpá", "Tabita"], c: 0, difficulty: "dificil"},
 /*18*/ { q: "¿Qué evento marcará el fin definitivo de Satanás?", a: ["Liberación final tras mil años", "Armagedón", "Juicio Inicial", "Primera resurrección", "No se sabe"], c: 0, difficulty: "dificil"},
 /*19*/ { q: "Según Mateo 24:34, “esta generación” se refiere a:", a: ["Los que vivieron en 33 e.C", "Dos grupos superpuestos de ungidos", "Los que vivieron en 1914", "Generación simbólica", "Los discípulos de Jesús"], c: 1, difficulty: "dificil"},
 /*20*/ { q: "Según Mateo 17:24-27, Pedro encontró una moneda en la boca de un pez. ¿De qué valor era la moneda?", a: ["Un estater", "Un denario", "Un dracma", "Un leptón", "Un asarion"], c: 0, difficulty: "dificil"},
 /*21*/ { q: "¿Qué hijo de Saúl llegó a ser rey después de su muerte?", a:["Jonatán", "Is-Bóset", "Mefibóset", "Isví", "Ninguno, poque David fue Rey"], c: 1, difficulty: "dificil"},
 /*22*/ { q: "¿Cuál de los siguientes personajes fue un discípulo de Jesús?", a:["Matusalén", "Tomás", "Barsabás", "Lucas", "Levi"], c: 4, difficulty: "dificil"},
 /*23*/ { q: "¿En qué campo fue enterrada Sara por su esposo Abrahán?", a:["Zoán", "Moab", "Bet-semes", "Macpelá", "No se sabe"], c: 3, difficulty: "dificil"},
 /*24*/ { q: "¿Cuantos años reinó David sobre Israel?", a:["40 años", "50 años", "35 años", "25 años", "60 años"], c: 0, difficulty: "dificil"},
 /*25*/ { q: "Jehová prometió a Abrahán que perdonaría a Sodoma y Gomorra si hallaba en ellas un número determinado de personas justas. ¿Cuál era ese número?", a:["5", "10", "3", "7", "20"], c: 1, difficulty: "dificil"},
 /*26*/ { q: "¿Cuántos hijos predijo Dios que tendría Ismael, hijo de Abrahaán", a:["10", "11", "12", "13", "15"], c: 2, difficulty: "dificil"},
 /*27*/ { q: "¿Qué nombre <span class='resaltar'>dio Raquel</span> a su segundo hijo poco antes de morir a consecuencia del parto?", a:["Rubén", "Simeón", "José", "Ben-Oní", "Benjamín"], c: 3, difficulty: "dificil"},
 /*28*/ { q: "¿Quién fue el padre de Jezabel?", a:["Neko", "Jeroboán", "Etbaal", "Nebat", "Acab"], c: 2, difficulty: "dificil"},
 /*29*/ { q: "Respecto a su vida personal, ¿cuál describe correctamente la relación de Charles Taze Russell con Maria Frances Ackley?", a:["Se casaron y permanecieron juntos hasta la muerte de él", "Erán madre e hijo", "Eran hermanos", "Se casaron, se separaron y luego se divorciaron", "No tenían ninguna relación"], c: 3, difficulty: "dificil"},
 /*30*/ { q: "¿Cuántos cancioneros diferentes han publicado los Testigos de Jehová a lo largo de su historia?", a:["9", "10", "11", "12", "13"], c: 4, difficulty: "dificil"},
 /*31*/ { q: "¿Cuándo se estrenó el Foto-Drama de la Creación?", a:["1914", "1919", "1916", "2000", "1864"], c: 0, difficulty: "dificil"},
 /*32*/ { q: "¿Cuál fue el primer nombre legal de la Watch Tower Bible and Tract Society of Pennsylvania?", a:["International Watch Tower Society", "Watch Tower Missionary Society", "Zion's Watch Tower", "Watch Tower Bible and Tract Society"], c: 2, difficulty: "dificil"},
 /*33*/ { q: "¿En qué año se construyó oficialmente el primer Salón del Reino?", a:["1928", "1935", "1942", "1930", "1940"], c: 1, difficulty: "dificil"},
 /*34*/ { q: "Hasta hace poco, los publicadores tenían que contar y reportar horas de predicación cada mes. ¿En qué año se eliminó oficialmente este requisito?", a:["2020", "2021", "2022", "2023", "2019"], c: 3, difficulty: "dificil"},
 /*35*/ { q: "Cierto o falso: el cambio para eliminar el informe de horas para los publicadores se basó en el diezmo.", a:["Cierto", "Falso"], c: 0, difficulty: "dificil"},
 /*36*/ { q: "Un hombre con un manto golpeó el río, las aguas se abrieron y pasó sin lío.Todos piensan en un mar que se partió, pero en este milagro solo él pasó.", a:["Elías", "Eliseo", "Moisés", "Josué", "Samuel"], c: 1, difficulty: "dificil"},
 /*37*/ { q: "Un hombre con su manto golpeó el río,las aguas se abrieron y cruzaron sin lío.Todos piensan en un mar que se partió,pero en este milagro juntos cruzaron los dos.", a:["Elías", "Eliseo", "Moisés", "Josué", "Samuel"], c: 0, difficulty: "dificil"},
 /*38*/ { q: "Del cielo cayó comida sin fin, sus quejas se convirtieron en festín. Muchos creen que todo era igual, pero solo uno llegó a ser mortal.", a:["El maná", "Las codornices", "Nnguno fue mortal", "Las tortas sin levadura", "La comida de Egipto"], c: 1, difficulty: "dificil"},
 /*39*/ { q: "Unos niños lo vieron y empezaron a reír, de su cabeza calva no podían resistir. Muchos creen que fue solo diversión, pero Dios intervino con firme decisión. ¿Quién fue objeto de la burla?", a:["Samuel", "Moisés", "Lamec", "Eliseo", "Isaac"], c: 3, difficulty: "dificil"},
 /*40*/ { q: "Cómo se les conocía antes a los superintendentes de circuito?", a: ["Viajeros", "Enviados", "Nobles", "Peregrinos", "Portavoces"], c: 3, difficulty: "dificil"},
 
]