const questionsFacil = [

  /*1*/ { q: "¿Cuántos libros tiene la Biblia en total?", a: ["39","66","69"], c: 1, difficulty: "facil" },
  /*2*/ { q: "¿Cuántas personas se salvaron en el arca de Moisés?", a: ["1", "8", "4"], c: 0, difficulty: "facil"},
  /*3*/ { q: "¿Qué juez de Israel tenía una fuerza extraordinaria?", a: ["Gedeón", "Sansón", "Goliat"], c: 1, difficulty: "facil"},
  /*4*/ { q: "¿Qué rey pidió sabiduría en vez de riquezas?", a: ["David", "Josías", "Salomón"], c: 2, difficulty: "facil"},
  /*5*/ { q: "¿Qué apóstol negó a Jesús 3 veces?", a: ["Tomás", "Pedro", "Judas"], c: 1, difficulty: "facil"},
  /*6*/ { q: "¿Cuál es el evangelio con menos capítulos?", a:["Mateo", "Marcos", "Lucas", "Juan"], c: 1, difficulty: "facil"},
  /*7*/ { q: "¿Cómo se llama el grupo de personas que dirige la organización a nivel mundial?", a: ["Ancianos de congregación", "Ungidos", "Cuerpo Gobernante"], c: 2, difficulty: "facil"},
  /*8*/ { q: "¿Cuántos hombre escribieron la Biblia?", a: ["44", "33", "40"], c: 2, difficulty: "facil"},
  /*9*/ { q: "Cierto o falso: el número <span class='resaltar'> total </span> de los hijos e hijas de Jacob fue de 12", a: ["Cierto", "Falso"], c: 1, difficulty: "facil"},
 /*10*/ { q: "¿Cuál es el séptimo libro de la Biblia?", a: ["Josué", "Esdras", "Jueces"], c: 2, difficulty: "facil"},
 /*11*/ { q: "¿Cuál es el libro de la Biblia que tiene más capítulos?", a: ["Salmos", "Proverbios", "Números"], c: 0, difficulty: "facil"},
 /*12*/ { q: "¿Cómo se les conoce a las 4 letras hebreas del nombre de Dios?", a: ["Pentagramaton", "Tetragrámaton", "Consonantes"], c: 1, difficulty: "facil"},
 /*13*/ { q: "¿Cuántas veces aparece el nombre de Dios en la Biblia?", a: ["144.000 veces", "156 veces", "7.000 veces"], c: 2, difficulty: "facil"},
 /*14*/ { q: "¿Qué es el Reino de Dios?", a: ["Un gobierno simbólico", "Un gobierno celestial", "Algo en el corazón"], c: 1, difficulty: "facil"},
 /*15*/ { q: "¿En qué año se adoptó el nombre de Testigos de Jehová?", a: ["1931", "1914", "1824"], c: 0, difficulty: "facil"},
 /*16*/ { q: "¿Quién se disgustó con Jehová por no haber destruido Nínive?", a:["Elías", "Jonás", "Esdras"], c: 1, difficulty: "facil"},
 /*17*/ { q: "¿Quién fue el padre de Juan el Bautista?", a:["Zorobabel", "Zacarías", "Sedequías"], c: 1, difficulty: "facil"},
 /*18*/ { q: "La curiosidad es vicio que debemos evitar, a quien no supo vencerlo el vicio le fue fatal ¿Quién fue?", a:["La esposa de Lot", "Judas", "David"], c: 0, difficulty: "facil"},
 /*19*/ { q: "Aunque estas llevan a la muerte, no siempre ocurrió así. Hubo una que dio vida, ¿de quién se habla aquí?", a:["El becerro de oro", "Las estatuas de plata", "La serpiente de cobre"], c: 2, difficulty: "facil"},
 /*20*/ { q: "Sansón fue el más fuerte, el más sabio Salomón, el más valiente fue David, pero, ¿a quién le duró más el corazón?", a:["Jacob", "Matusalén", "Adán"], c: 1, difficulty: "facil"},
 /*21*/ { q: "Mala reputación ella tenía, pero en Jehová confió, por su fe se salvaría al llegar la destrucción, ¿Quién fue?", a:["Rahab", "María", "La hija de Jefté"], c: 0, difficulty: "facil"},
 /*22*/ { q: "Aunque sea muy pequeña no es pequeño su poder, pues por más pequeña que sea, grandes cosas puede hacer. ¿Qué es?", a:["La oración", "La Biblia", "La fe"], c: 2, difficulty: "facil"},
 /*23*/ { q: "No por un diluvio, sino por ser salvador, siendo muy joven entró en el arca, sin saber que más tarde cruzaría el mar sin necesidad de una barca. ¿Quién fue?", a:["Noé", "Moisés", "Jesús"], c: 1, difficulty: "facil"},
 /*24*/ { q: "No murió en el agua, aunque estuvo rodeado por ella; no usó arma, pero derrotó a un ejército. ¿Quién fue?", a:["Moisés", "Gedeón", "David"], c: 0, difficulty: "facil"},
 /*25*/ { q: "Fue profeta sin escribir profecía, hizo caer fuego del cielo y no conoció la muerte. ¿Quién fue?", a:["Eliseo", "Ezequiel", "Elías"], c: 2, difficulty: "facil"},
 /*26*/ { q: "De Goliat el antónimo, de fiel y arrepentido el sinónimo. ¿Quién fue?", a:["Jesús", "Zaqueo", "Pedro"], c: 1, difficulty: "facil"},
 /*27*/ { q: "Un hombre habló y el sol no se ocultó; otro habló y el sol cambió su curso. No fue una orden de guerra ni un mandato público, sino una señal pedida en silencio. ¿Quién fue?", a:["Ezequías", "Josué", "Elías"], c: 0, difficulty: "facil"},
 /*28*/ { q: "¿Cuántos días tardó Jehová en crear todas las cosas? ", a:["7", "5", "6"], c: 2, difficulty: "facil"},
 /*29*/ { q: "¿Cuántos panes y peces usó Jesús para alimentar a las 5000 personas?", a:["2 panes y 5 peces", "5 panes y 2 peces", "5 panes y 5 peces"], c: 1, difficulty: "facil"},
 /*30*/ { q: "¿Qué ciudad es conocida como la ciudad de David?", a:["Belén", "Jerusalén", "Hebrón"], c: 1, difficulty: "facil"},


]