const questionsMedia = [

  /*1*/ { q: "El Alfa y el Omega son títulos de…", a: ["Jesús","Jehová","Satanás"], c: 1, difficulty: "media" },
  /*2*/ { q: "La viuda que observó Jesús en el templo echo...", a: ["Un denario", "Un leptón", "Un talento", "Un cuadrante"], c: 3, difficulty: "media"},
  /*3*/ { q: "¿Cuántos libros tienen las Escrituras Griegas Cristianas?", a: ["29", "33", "27", "19"], c: 2, difficulty: "media"},
  /*4*/ { q: "¿Cuál de los siguientes ríos NO pertenece a los ríos del jardín de Edén? ", a: ["Pisón", "Guihon", "Hidequel", "Arnón"], c: 3, difficulty: "media"},
  /*5*/ { q: "¿Quién escribió la mayoría de los Salmos?", a: ["Moisés", "Asaf", "Salomón", "Jonatán", "David"], c: 4, difficulty: "media"},
  /*6*/ { q: "¿En qué monte recibió Moisés los Diez Mandamientos?", a: ["Monte Carmelo", "Monte de Edom", "Monte Elevado", "Monte Sinaí", "Monte Guilgal"], c: 3, difficulty: "media"},
  /*7*/ { q: "Cierto o Falso. Homer fué la esposa de Oseas", a: ["Falso", "Cierto"], c: 0, difficulty: "media"},
  /*8*/ { q: "¿Con qué otro nombre se le conoce al lago de fuego?", a: ["El abismo", "La muerte celestial", "La muerte segunda", "El abismo ardiente", "El lamento eterno"], c: 2, difficulty: "media"},
  /*9*/ { q: "Leviatán es un tipo de animal...", a: ["Acuático", " Terrestre", "Aéro", "Aéreo-terrestre"], c: 0, difficulty: "media"},
 /*10*/ { q: "¿Con qué nombre se le conocía antes a la revista Despertad?", a: ["Eternal life", "The word of God", "A cry from the sky", "Zion's Watch Tower", "The Golden Age"], c: 4, difficulty: "media"},
 /*11*/ { q: "¿En qué año se dijo esta frase: 'Anuncien, anuncien, anuncien al Rey y su reino'?", a: ["2000", "1914", "1931", "1922", "1919"], c: 3, difficulty: "media"},
 /*12*/ { q: "¿Con qué nombre se le conocía antes a los precursores?", a: ["Subditos", "Gramofoneros", "Predicadores", "Ministros", "Colportores"], c: 4, difficulty: "media"},
 /*13*/ { q: "¿A quién representa en el hombre con el tintero de Secretario?", a: ["A los ungidos que quedan en la tierra", "A Jesús", "A Jehová", "A los ángeles", "A los ancianos de congregación"], c: 1, difficulty: "media"},
 /*14*/ { q: "¿Cómo se les conocía antes a los superintendentes de circuito?", a: ["Viajeros", "Enviados", "Nobles", "Peregrinos", "Portavoces"], c: 3, difficulty: "media"},
 /*15*/ { q: "¿Cómo se le conoce ahora a lo que antes se llamaba Círculos Bereanos para Estudios Bíblicos?", a: ["Cursos bíblicos", "Reunión Vida y Ministerio Cristianos", "Discurso Público", "Estudio Bíblico de la Congregación"], c: 3, difficulty: "media"},
 /*16*/ { q: "El templo de Salomón tenía dos columnas. ¿Cuál es el significado de sus nombres?", a:["Dios proveerá a los justos", "Que Él establezca firmemente con fuerza", "Que Dios tenga la gloria", "La casa del Dios de Israel"], c: 1, difficulty: "media"},
 /*17*/ { q: "¿Qué joven fue a buscar burros y terminó convirtiéndose en rey al regresar a casa?", a:["David", "Jehú", "Saúl", "Sedequías"], c: 2, difficulty: "media"},
 /*18*/ { q: "¿Qué rey de Israel fue conocido por conducir su carro de  guerra como un loco?", a:["Saúl", "David", "Mardoqueo", "Jehú"], c: 3, difficulty: "media"},
 /*19*/ { q: "En Meribá, Moisés y Aarón sacaron agua de un peñasco. ¿Qué les dijo Jehová que hicieran para que saliera agua?", a:["Golpearla dos veces", "Orar en voz alta", "Hablarle al peñasco", "Golpearla tres veces"], c: 2, difficulty: "media"},
 /*20*/ { q: "En que monte Elías confrontó a 450 profetas de Baal?", a:["Monte Carmelo", "Monte de Ararat", "Monte Hermón", "Monte de Baal"], c: 0, difficulty: "media"},
 /*21*/ { q: "¿En qué rio fue bautizado Jesús?", a:["Río Nilo", "Río Éufraes", "Río Jordán", "Río Jabor"], c: 2, difficulty: "media"},
 /*22*/ { q: "¿Cómo se llamaba el lugar dónde murió Jesús?", a:["Valle del Gehena", "Valle de Hinón", "Sinaí", "Gólgota"], c: 3, difficulty: "media"},
 /*23*/ { q: "¿Qué juez mató a 600 filisteos con una aguijada?", a:["Sansón", "Gedeón", "Samgar", "Otniel"], c: 2, difficulty: "media"},
 /*24*/ { q: "¿Cómo se llamaba el primer esposo de Rut?", a:["Obed", "Mahlón", "Boaz", "Urías"], c: 1, difficulty: "media"},
 /*25*/ { q: "En cumplimiento de la palabra de Jehová. ¿qué animales devoraron a la malvada Jezabel?", a:["Cuervos", "Osos", "Leones", "Perros"], c: 3, difficulty: "media"},
 /*26*/ { q: "¿Qué gobernador romano retuvo preso al apóstol Pablo durate dos años esperando recibir un soborno de él?", a:["Festo", "Agripa", "Félix", "Claudio"], c: 2, difficulty: "media"},
 /*27*/ { q: "¿qué parte de la armadura cristiana que describió Pablo simboliza la salvación?", a:["El cinturón", "El casco", "La corazá", "El calzado"], c: 1, difficulty: "media"},
 /*28*/ { q: "¿Cuál de los tres compañeros de Daniel recibió el nombre de Mesac?", a:["Misael", "Hananías", "Abednego", "Beltsasar"], c: 0, difficulty: "media"},
 /*29*/ { q: "David era joven y valiente, venció a un gigante con una honda. El hermano del gigante murió, pero no por la mano del joven pastor. ¿Quién lo derrotó?", a:["Jair", "Sibecaí", "Elhanán", "Sipái"], c: 2, difficulty: "media"},
 /*30*/ { q: "¿Cuál es el evangelio con menos capítulos?", a:["Mateo", "Marcos", "Lucas", "Juan"], c: 1, difficulty: "media"},



]